project_id = "auntkvllzejtfqmousxg"

[functions.send-auth-email]
verify_jwt = false

[functions.xaut-price-collector]
verify_jwt = false

[functions.gold-price-public-api]
verify_jwt = false

[functions.contract-deployment]
verify_jwt = true

[functions.populate-test-data]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
port = 54322
shadow_port = 54320
max_connections = 100

[functions.gold-price-api]
verify_jwt = false

[functions.metals-price-api]
verify_jwt = false

[functions.moonpay-buy]
verify_jwt = true

[functions.moonpay-sell]
verify_jwt = true

[functions.moonpay-webhook]
verify_jwt = false

[functions.blockchain-operations]
verify_jwt = true

[functions.fee-collection-webhook]
verify_jwt = false

[functions.fee-collection-api]
verify_jwt = false

[functions.moonpay-diagnostics]
verify_jwt = true

[functions.security-health-check]
verify_jwt = true

[functions.security-monitor]
verify_jwt = true

[functions.moonpay-status]
verify_jwt = true

[functions.financial-news-collector]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.ai]
verify_jwt = true

[functions.trigger-news-collection]
verify_jwt = true

[functions.verify-balances]
verify_jwt = false

[functions.moonpay-proxy]
verify_jwt = true

[functions.reconcile-transactions]
verify_jwt = false

[functions.swap-intent-reconciliation]
verify_jwt = false

[functions.send-support-email]
verify_jwt = true

[functions.transfer-to-dydx]
verify_jwt = true

[functions.monitor-squid-deposits]
verify_jwt = false

[functions.record-skip-withdrawal]
verify_jwt = true

[functions.dydx-trading]
verify_jwt = true

[functions.dydx-market-data]
verify_jwt = false

[functions.check-dydx-balance]
verify_jwt = false

[functions.sync-dydx-positions]
verify_jwt = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
